### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by w0am1** [MuTsunTsai/fontfreeze#1]
I tried freezing couple of features (use alternate variant of @ and &) of fira font, but in the generated ttf file both the glyps are still same as the default variant.

**Comment by MuTsunTsai** [comment]
Hello! Fira Code in particular has been quite thoroughly tested with this app as I also use it myself, so I'm sure we can figure this out. I suppose you checked `ss03` and `ss05`, yes? Could you provide the following info:
1. Which font file you used as base (e.g. FiraCode-Regular.ttf), and is it the latest version?
2. Did you try reopen the generated TTF file in FontFreeze, and is it working as expected?
3. If it's working in FontFreeze but not somewhere else, what is your environment?

**Comment by w0am1** [comment]
> Hello! Fira Code in particular has been quite thoroughly tested with this app as I also use it myself, so I'm sure we can figure this out. I suppose you checked `ss03` and `ss05`, yes? Could you provide the following info:
> 
> 1. Which font file you used as base (e.g. FiraCode-Regular.ttf), and is it the latest version?
> 2. Did you try reopen the generated TTF file in FontFreeze, and is it working as expected?
> 3. If it's working in FontFreeze but not somewhere else, what is your environment?

Yes I have checked ss03 and ss05 and I have been using Fira Font's latest version v6.2. When I reopen the generated TTF file in fontFreeze, the preview is as expected. But when I open the same TTF file in fontforge app or use it in notepad++, then I don't see the glyphs changed.

**Comment by MuTsunTsai** [comment]
It is the correct behavior that you won't see glyph changes in FontForge because that's not how FontFreeze force activating the features (see readme for more details). I don't use Notepad++ myself, but my understanding is that it doesn't natively support coding ligatures, so the default activation method of FontFreeze won't work with it. Could you try changing the “Target feature for activation” setting to `rvrn` and see if it works on Notepad++? If it still doesn't, check out this instruction and see if it helps:
https://github.com/tonsky/FiraCode/wiki/Notepad-Plus-Plus-instructions

**Comment by w0am1** [comment]
Ok got it. After following the link I can see the new @ and & in notepad++. I was thinking by default on any editor this should show the alternate variant of @ and & without needing to enable ligature.

**Comment by MuTsunTsai** [comment]
It works directly on Chrome, VS Code, Visual Studio, Android Studio, and PowerShell at least. Notepad++ seems to be an exception that doesn't strictly follow OpenType specifications. Maybe you can report an issue to them.

**Comment by MuTsunTsai** [comment]
Meanwhile, I can also try to implement actual glyph subsitituion (when it comes to features involving just a single character) in the next version for maximal compatibility. I've created an new issue #2 to track this.

**Comment by MuTsunTsai** [comment]
@w0am1 The new feature is now on in v1.3. I've tested with Fira Code + ss03-05, and the generated font works in Notepad++ without additional settings.

**Comment by w0am1** [comment]
> @w0am1 The new feature is now on in v1.3. I've tested with Fira Code + ss03-05, and the generated font works in Notepad++ without additional settings. If you found this app helpful, please star and spread the news to others 😁

Checked with v1.3 and it works perfectly. Thanks 👍 :)
