### ISSUE TITLE
Exception when freezing "cv" features on fonts missing "calt" table.

### ISSUE THREAD

**Issue by AndyDagnall** [MuTsunTsai/fontfreeze#11]
This is a great tool to "freeze" the open types features of a font, but I've encountered some errors in freezing "cv" features on some fonts, where the "calt" table is not present, similar to the issue that another user found with freezing "ss" features on such fonts which you have already fixed.

Steps to reproduce:

* Download the ttf version of the font: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.042R-u%2F1.062R-i%2F1.026R-vf
* Load SourceCodePro-Regular.ttf in the freezer
* Select cv01 or any other character variant
* Click "Generate font!"
* A python exception occurs

I would perhaps tentatively suggest the following fix to `main.py`.
* In the code dealing with "no existing one", insert `featureParamTypes[self.target] = FeatureParamsStylisticSet if featureRecord.FeatureTag.startswith("ss") else FeatureParamsCharacterVariants` before `featureRecord.FeatureTag = self.target`.
* Update the imports to include `FeatureParamsCharacterVariants`.
* The line that previously set `featureParamTypes['calt']` can be removed.

**Comment by MuTsunTsai** [comment]
Ahha, you've got it all figured out! That was easy for me. I've made the suggested changes. Thanks!
