### ISSUE TITLE
Support additional font weights

### ISSUE THREAD

**Issue by abhiramakella** [MuTsunTsai/fontfreeze#12]

**Comment by MuTsunTsai** [comment]
Not entirely sure what you mean by that, but in any case the font weights are defined by the fonts themselves and there's nothing I can do.

**Comment by gesly** [comment]
I think the reference here maybe to the font subfamily which is fixed. On a macos, this causes a duplicate issue when installing weights such as Light, Medium

**Comment by abhiramakella** [comment]
Well there are additional font weights such as Semibold, Black, Medium, Light, Thin, etc.

**Comment by abhiramakella** [comment]
This is a reference to #5.
