### ISSUE TITLE
When I processed the font file with Fontfreeze, the version information was lost

### ISSUE THREAD

**Issue by rocex** [MuTsunTsai/fontfreeze#15]
![20240930092635](https://github.com/user-attachments/assets/307dbd8b-1578-4c3d-b6fa-556a52b949bd)

**Comment by MuTsunTsai** [comment]
That is somewhat intentional, for, as far as I remember, derived fonts are supposed to reset the version number (and only refer to the original version numbers in their descriptions if necessary). In all cases, it shouldn't cause any problem in using the generated font.
