### ISSUE TITLE
Ligatures not freezed when using exported font on web

### ISSUE THREAD

**Issue by ckcherry23** [MuTsunTsai/fontfreeze#16]
I tried generating a font with `dlig` and `ss07` options. 

On the preview, everything looks exactly as expected.
![Screenshot 2024-10-15 at 1 35 39 PM](https://github.com/user-attachments/assets/3e3355a4-17aa-4db9-a34d-cd949400a2f6)

But when using the exported font in a React website, the `ss07` stylistic set is applied, but the `dlig` ligatures do not appear.

For example, notice the "fl" (the horizontal dash in f should be connected to l) and "fff" (first 2 f's must be connected, but not 3rd one).

<img width="1288" alt="Screenshot 2024-10-15 at 1 41 02 PM" src="https://github.com/user-attachments/assets/4f1f8066-c058-45dc-9ba0-c0efe4256afb">

I've tried just using `dlig` without other settings, but the ligatures are still not applied. Is there any reason for the preview to work correctly but using the exported font in a website to have issues?

Update: 
* The exported frozen font works correctly when used on FontBook. The issue is when used on the website. However, when we use our own variable font instead and set the font feature settings in Tailwind, it works correctly.

---

<details>
<summary>These are the settings used:</summary>

![Screenshot 2024-10-15 at 1 33 33 PM](https://github.com/user-attachments/assets/d9bd7df8-6728-4524-b698-ce0a4cb96406)

</details>

**Comment by MuTsunTsai** [comment]
I'm guessing that you are probably unable to provide the font in question for inspection. Well, what do you see if you load the generated font back into the FontFreeze app?
In any case, since you're using the font in websites, you can always just use CSS to control the font features ([reference](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings), and BTW, that's exactly how the preview works here) and you probably don't need to use FontFreeze in the first place.

**Comment by ckcherry23** [comment]
Thanks for getting back @MuTsunTsai! 

The generated font works correctly when uploaded back to the FontFreeze app. The issue is when using it on our website.

The reason I wanted to freeze the font is so that our OG images can use them, because font feature settings are not supported in Next.js OG images. I thought freezing the font would help overcome this.

![image](https://github.com/user-attachments/assets/04b38d77-4b34-4a21-ba5f-79cb5220c89e)
Source: https://www.npmjs.com/package/satori/v/0.9.0
