### ISSUE TITLE
glyphs disabled for Fira Code v6.2

### ISSUE THREAD

**Issue by FaiyazMujawar** [MuTsunTsai/fontfreeze#6]
Hi,
I tried freezing with the following glyph settings, when downloaded the glyps for !=,==, =>, -> etc are all disabled,, or not working.

I'd like to know if I'm doing any mistake.

Thanks!

![image](https://user-images.githubusercontent.com/54775619/223683269-0d8a4216-cfc0-46b8-a7fa-9793a9a52b66.png)

**Comment by MuTsunTsai** [comment]
You should leave `calt` unchecked. That should do it.

**Comment by FaiyazMujawar** [comment]
> You should leave `calt` unchecked. That should do it.

thanks! it worked!

**Comment by MuTsunTsai** [comment]
@FaiyazMujawar Glad to hear that. Please star this repo and tell your friends about it if you found the app helpful 😁
