### ISSUE TITLE
OverflowError: unsigned byte integer is greater than maximum

### ISSUE THREAD

**Issue by sonulohani** [MuTsunTsai/fontfreeze#7]
I am using font MapleMono https://github.com/subframe7536/Maple-font/releases/tag/v6.2
and I see this issue
![image](https://user-images.githubusercontent.com/2958681/231939127-2ce11da3-ea74-4991-ba4b-ee668104c505.png)

**Comment by MuTsunTsai** [comment]
Thanks for reporting the issue. This error appears to have more to do with the font itself, as the error basically means the some of the glyphs in the font are having ids greater than they should. I've tried to process the font with several other font-related softwares (such as FontForge) without success. You'll probably have to report the issue to the creators of the font.

**Comment by sonulohani** [comment]
Done
